// This file will be auto-generated by Supabase CLI
// For now, we'll use a placeholder type
// Once your Supabase project is set up, run:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            // Tables will be auto-generated here
            [key: string]: {
                Row: Record<string, unknown>
                Insert: Record<string, unknown>
                Update: Record<string, unknown>
            }
        }
        Views: {
            [key: string]: {
                Row: Record<string, unknown>
            }
        }
        Functions: {
            [key: string]: unknown
        }
        Enums: {
            [key: string]: string
        }
    }
}
